### ISSUE TITLE
Installing D4RL using pip install -e causes error

### ISSUE THREAD

**Issue by kamranramji** [rail-berkeley/d4rl#49] opened 2020-09-01 21:22 UTC
How to reproduce:
git clone https://github.com/rail-berkeley/d4rl.git
cd d4rl
pip install -e .

Error message text: 

Exception:
Traceback (most recent call last):
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/kamran/rlfd_env/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/home/kamran/rlfd_env/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/mjrl/

Thanks in advance for the help.

**Comment by Ericonaldo** [comment] 2020-09-11 07:54
Install mjrl by hand can solve this problem. pip install git+git://github.com/aravindr93/mjrl@master#egg=mjrl

**Comment by justinjfu** [comment] 2020-11-03 01:29
Closing for now; I'm unable to reproduce this issue but the above tip can be useful for those running into it.

**Closed by justinjfu** 2020-11-03 01:29 UTC
